stbt power: Check and print new status after switching on/off
The exit status (and the standard output) now reflect whether the
outlet's new status is the same as the status you requested. Before, the
command might fail with no indication that it had failed.

The sleep is necessary because the previous command returns before the
change actually takes effect.

diff --git a/stbt-power b/stbt-power
--- a/stbt-power
+++ b/stbt-power
@@ -118,6 +118,15 @@ pdu() {
     sed -En '/ON|OFF/ p' |
     tail -n +2 ||
     die "failed to connect to '$hostname'"
+
+    [[ $command == status ]] || {
+        sleep 2
+        local output=$(pdu status $hostname $outlet | grep -i "$outlet")
+        [[ -n "$output" ]] ||
+            die "invalid outlet '$outlet' (hint: use the 'status' command)"
+        echo "$output"
+        echo "$output" | grep -qi "$command" || exit 1
+    }
 }
 
 main "$@"
