extra/runner/report: Debug for "skipping in-progress test" includes directory name
Also use `echo "$rundir: ...` explicitly instead of the function `debug`
because to call `debug` you had to know whether the `rundir` variable
was set to the right value. There is already a lot of global state and
tight coupling in these scripts, but every little improvement helps. :-)

diff --git a/extra/runner/report b/extra/runner/report
--- a/extra/runner/report
+++ b/extra/runner/report
@@ -33,14 +33,16 @@ main() {
     (
       [[ "$rundir" =~ index.html$ ]] && return 0  # Summary report only
       cd "$rundir" || die "Invalid directory '$rundir'"
-      [ -r exit-status ] ||
-        { echo "No exit status (test still in progress); skipping"; return 0; }
+      [ -r exit-status ] || {
+        echo "$rundir: No exit status (test still in progress); skipping"
+        return 0
+      }
 
       if $do_classify; then
         classify > failure-reason
         sort --merge stdout.log stderr.log > combined.log
         user_command classify
-        debug "$(cat failure-reason)"
+        echo "$rundir: $(cat failure-reason)"
       fi
 
       if $do_html; then
@@ -99,7 +101,6 @@ user_command() {
   "$c"
 }
 
-debug() { echo "$rundir: $*"; }
 die() { echo "$(basename "$0"): error: $*" >&2; exit 1; }
 
 # Portable implementation of GNU "readlink -f" to support BSD/OSX.
