extra/runner: Show shorter relative path to test script in report
The table in the report is already short on horizontal space, so we want
the test name to be as short as possible, but still unambiguous. I
assume that the test script is in a git repository, and I use the path
of the script relative to the repository root. We can support other
source control systems as the need arises.

I could have used `git rev-parse --show-toplevel` instead of
`--git-dir`, but that requires git v1.7.0 (whereas `--git-dir` exists
since v1.0).

diff --git a/extra/runner/run b/extra/runner/run
--- a/extra/runner/run
+++ b/extra/runner/run
@@ -67,8 +67,7 @@ run() {
   mkdir "$rundir" &&
   rm -f current"$tag" && ln -s "$rundir" current"$tag" &&
   cd "$rundir" &&
-  mkfifo rawout rawerr &&
-  echo "$_test" > test-name ||
+  mkfifo rawout rawerr ||
   die "Failed to set up test-run directory '$rundir'."
 
   [ -n "$tag" ] && echo "Tag	${tag#-}" > extra-columns
@@ -77,6 +76,12 @@ run() {
     git describe --always --dirty
   ) > git-commit ||
   die "Failed to determine the test script's git revision."
+
+  ( cd "$(dirname "$_test")" &&
+    gitdir=$(dirname "$(abspath "$(git rev-parse --git-dir)")") &&
+    echo "${_test#$gitdir/}"
+  ) > test-name ||
+  die "Failed to determine the test script's path relative to its git repo."
 
   [ $verbose -gt 0 ] && printf "\n$test...\n" || printf "$test... "
   PYTHONUNBUFFERED=x \
